sonar.projectKey=DEFRA_batteries-producer-frontend
sonar.organization=defra

sonar.links.homepage=https://github.com/DEFRA/batteries-producer-frontend
sonar.links.ci=https://github.com/DEFRA/batteries-producer-frontend/actions
sonar.links.scm=https://github.com/DEFRA/batteries-producer-frontend
sonar.links.issue=https://github.com/DEFRA/batteries-producer-frontend/issues

sonar.sources=src/
sonar.exclusions=src/**/*.test.js,src/test-utils/**/*.*,src/config/content.js,src/client/javascripts/**
sonar.tests=src/
sonar.test.inclusions=src/**/*.test.js
sonar.javascript.lcov.reportPaths=./coverage/lcov.info
sonar.cpd.exclusions=src/**/*.test.js,src/server/**/*controller*.js
